"""added user_id to Document

Revision ID: 27cc64092c36
Revises: ebc0a2babb91
Create Date: 2026-02-10 13:34:56.247853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cc64092c36'
down_revision: Union[str, Sequence[str], None] = 'ebc0a2babb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
