"""added user_id to Document

Revision ID: ebc0a2babb91
Revises: a7b4575bfcf8
Create Date: 2026-02-10 12:28:07.518480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc0a2babb91'
down_revision: Union[str, Sequence[str], None] = 'a7b4575bfcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
